config/routes.rb
Rails.application.routes.draw do

  resources :executes
  resources :keywords
  resources :platforms

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
  }

  resources :users
  resources :manages
  resources :roles, except: :show
  resources :projects
  resources :assigns
  resources :suites , except: :show do
    resources :cases , except: :show do
      resources :steps, except: [:show, :edit]
    end
  end

  resources :builds , except: :show do
    resources :plans , except: :show do
      resources :case_plan , except: :show
    end
  end

  resources :message_folders do
    resources :messages
  end

  post '/set_current_project', to: 'application#set_current_project', as: :set_current_project
  post '/save_execution', to: 'executes#save_execution', as: :save_execution
  get 'case_plan/index'
  get '/executes_history', to: 'executes#index_history', as: :index_history
  get '/executes_history/:id', to: 'executes#show_index_history', as: :show_index_history


  root 'welcome#index'

end

app/models/assign.rb
class Assign < ApplicationRecord
end

app/models/build.rb
class Build < ApplicationRecord

  belongs_to :project
  has_many :plans

end

app/models/case.rb
class Case < ApplicationRecord

  belongs_to :suite
  has_many :steps
  has_many :case_plans

end

app/models/case_plan.rb
class CasePlan < ApplicationRecord
  belongs_to :user
  belongs_to :case
  belongs_to :plan
end

app/models/execute.rb
class Execute < ApplicationRecord
end

app/models/execute_case.rb
class ExecuteCase < ApplicationRecord

  belongs_to :user
  has_many :execute_step

end

app/models/execute_step.rb
class ExecuteStep < ApplicationRecord

  belongs_to :execute_case

end

app/models/keyword.rb
class Keyword < ApplicationRecord
end

app/models/manage.rb
class Manage < ApplicationRecord

  # Relaciones
  belongs_to :role
  belongs_to :zone

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
end

app/models/plan.rb
class Plan < ApplicationRecord

  belongs_to :build
  has_many :case_plans

end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :assign
  has_many :builds

end

app/models/role.rb
class Role < ApplicationRecord

  # Relaciones
  has_many :users
  has_many :manages


  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10}

end

app/models/step.rb
class Step < ApplicationRecord

  belongs_to :case

end

app/models/suite.rb
class Suite < ApplicationRecord

  has_many :cases

end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Dirty
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable

  # attr_accessor :manages

  # Relaciones
  belongs_to :role
  has_many :assign
  has_many :message_folders
  has_many :case_plans

  after_initialize do |user|
    unless user.role.nil?
      @manages ||= Manage.where(:role_id => user.role.id)
    end
  end


  def CanRead?(zone)
    # @CanRead = Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canRead)
    # @manages.where(:zone_id => zone).select(:canRead).first
    @manages.select { |manage| manage.zone_id == zone }.first[:canRead]
  end

  def CanCreate?(zone)
    # @CanCreate ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canCreate)
    @manages.select { |manage| manage.zone_id == zone }.first[:canCreate]
  end

  def CanUpdate?(zone)
    # @CanUpdate ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canUpdate)
    @manages.select { |manage| manage.zone_id == zone }.first[:canUpdate]
  end

  def CanDelete?(zone)
    # @CanDelete ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canDelete)
    @manages.select { |manage| manage.zone_id == zone }.first[:canDelete]
  end


  private

  # def getManage
  #   @manages ||= Manage.where(:role_id => self.role.id)
  # end

end

app/models/zone.rb
class Zone < ApplicationRecord

  # Relaciones
  has_many :manages

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :param_folder

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where('message_folder_id' => @folder.id)
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subjet, :body)
    end

    def param_folder
      @folder = MessageFolder.find(params[:message_folder_id])
    end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subjet %>
    <%= f.text_field :subjet %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1><%= @folder.name %>: Messages</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th>Subjet</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @messages.each do |message| %>
        <tr>
          <td><%= message.subjet %></td>
          <td><%= message.body %></td>
          <td><%= link_to 'Edit', edit_message_folder_message_path(id: message.id, folder_id: @folder.id) %></td>
          <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subjet:</strong>
  <%= @message.subjet %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>