config/routes.rb
Rails.application.routes.draw do

  resources :executes
  resources :keywords
  resources :platforms

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
  }

  resources :users
  resources :manages
  resources :roles, except: :show
  resources :projects
  resources :assigns
  resources :suites , except: :show do
    resources :cases , except: :show do
      resources :steps, except: [:show, :edit]
    end
  end

  resources :builds , except: :show do
    resources :plans , except: :show do
      resources :case_plan , except: :show
    end
  end

  resources :message_folders do
    resources :messages
  end

  post '/set_current_project', to: 'application#set_current_project', as: :set_current_project
  post '/save_execution', to: 'executes#save_execution', as: :save_execution
  get 'case_plan/index'
  get '/executes_history', to: 'executes#index_history', as: :index_history
  get '/executes_history/:id', to: 'executes#show_index_history', as: :show_index_history


  root 'welcome#index'

end

app/models/assign.rb
class Assign < ApplicationRecord
end

app/models/build.rb
class Build < ApplicationRecord

  belongs_to :project
  has_many :plans

end

app/models/case.rb
class Case < ApplicationRecord

  belongs_to :suite
  has_many :steps
  has_many :case_plans

end

app/models/case_plan.rb
class CasePlan < ApplicationRecord
  belongs_to :user
  belongs_to :case
  belongs_to :plan
end

app/models/execute.rb
class Execute < ApplicationRecord
end

app/models/execute_case.rb
class ExecuteCase < ApplicationRecord

  belongs_to :user
  has_many :execute_step

end

app/models/execute_step.rb
class ExecuteStep < ApplicationRecord

  belongs_to :execute_case

end

app/models/keyword.rb
class Keyword < ApplicationRecord
end

app/models/manage.rb
class Manage < ApplicationRecord

  # Relaciones
  belongs_to :role
  belongs_to :zone

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
end

app/models/plan.rb
class Plan < ApplicationRecord

  belongs_to :build
  has_many :case_plans

end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :assign
  has_many :builds

end

app/models/role.rb
class Role < ApplicationRecord

  # Relaciones
  has_many :users
  has_many :manages


  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10}

end

app/models/step.rb
class Step < ApplicationRecord

  belongs_to :case

end

app/models/suite.rb
class Suite < ApplicationRecord

  has_many :cases

end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Dirty
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable

  # attr_accessor :manages

  # Relaciones
  belongs_to :role
  has_many :assign
  has_many :message_folders
  has_many :case_plans

  after_initialize do |user|
    unless user.role.nil?
      @manages ||= Manage.where(:role_id => user.role.id)
    end
  end


  def CanRead?(zone)
    # @CanRead = Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canRead)
    # @manages.where(:zone_id => zone).select(:canRead).first
    @manages.select { |manage| manage.zone_id == zone }.first[:canRead]
  end

  def CanCreate?(zone)
    # @CanCreate ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canCreate)
    @manages.select { |manage| manage.zone_id == zone }.first[:canCreate]
  end

  def CanUpdate?(zone)
    # @CanUpdate ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canUpdate)
    @manages.select { |manage| manage.zone_id == zone }.first[:canUpdate]
  end

  def CanDelete?(zone)
    # @CanDelete ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canDelete)
    @manages.select { |manage| manage.zone_id == zone }.first[:canDelete]
  end


  private

  # def getManage
  #   @manages ||= Manage.where(:role_id => self.role.id)
  # end

end

app/models/zone.rb
class Zone < ApplicationRecord

  # Relaciones
  has_many :manages

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:edit, :update, :destroy]
  before_action :param_suite
  before_action :authenticate_user!

  # GET /suite/cases
  def index
    @cases = Case.where('suite_id' => @suite.id)
  end

  # GET /suite/cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  def create
    @case = Case.new(case_params)
    @case.suite = @suite

      if @case.save
        flash[:success] = t('caseCreated')
        redirect_to suite_cases_path
      else
        flash[:error] = t('caseCreatedError')
        redirect_to new_suite_case_path
      end
  end

  # PATCH/PUT /cases/1
  def update
    if @case.update(case_params)
      flash[:success] = t('caseEdited')
      redirect_to suite_cases_path
    else
      flash[:error] = t('caseEditedError')
      redirect_to new_suite_case_path
    end
  end

  # DELETE /cases/1
  def destroy
    if @case.destroy
      flash[:success] = t('caseDeleted')
      redirect_to suite_cases_path
    else
      flash[:error] = t('caseDeletedError')
      redirect_to suite_cases_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:id])
    end

    def param_suite
      @suite = Suite.find(params[:suite_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_params
      params.require(:case).permit(:title, :description, :precondition, :timeEstimated, :suite_id)
    end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/cases/_form.html.erb
<div class="forms center-block" style="width: 60%;">
  <%= form_for([@suite, @case], :html => {:class => 'form-horizontal'}) do |f| %>
      <% if @case.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

            <ul>
              <% @case.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :ftitle, t('caseTitle'), class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, placeholder: t('caseTitle'), class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fdescription, t('caseDescription'), class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :description, placeholder: t('caseDescription'), class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fprecondition, 'Precondition', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :precondition, placeholder: 'Precondition', class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :ftimeEstimated, 'Time estimated', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :timeEstimated, placeholder: 'Time estimated', class: 'form-control' %>
        </div>
      </div>

      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit t('save'), class: "btn btn-default btn-primary" %>
        <%= link_to t('back'), suite_cases_path(suite_id: @suite.id), class: "btn btn-default" %>
      </div>

  <% end %>
</div>

app/views/cases/edit.html.erb
<h1><%= t('caseEdit') %> <%= @case.title %> </h1>
<%= render 'form', case: @case %>

app/views/cases/index.html.erb
<h1><%= t('cases') %></h1>

<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th><%= t('caseTitle') %></th>
      <th>Precondition</th>
      <th>Time estimated</th>
      <th colspan="4"><%= t('caseDescription') %></th>
    </tr>
    </thead>

    <tbody>
    <% @cases.each do |casee| %>
        <tr>
          <td class="col-md-3"><%= casee.title %></td>
          <td class="col-md-2"><%= casee.precondition %></td>
          <td class="col-md-2"><%= casee.timeEstimated %></td>
          <td class="col-md-5"><%= casee.description %></td>
          <td title="<%= t('caseEditList') %>"><%= link_to fa_icon("pencil") , edit_suite_case_path(suite_id: casee.suite.id, id: casee.id) %></td>
          <td title="<%= t('caseDeleteList') %>"><%= link_to fa_icon("remove") , suite_case_path(suite_id: casee.suite.id, id: casee.id), method: :delete, data: { confirm: t('confirmDelete') } %></td>
          <td title="<%= t('caseStepList') %>"><%= link_to fa_icon("vcard-o") , suite_case_steps_path(suite_id: casee.suite.id, case_id: casee.id) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/cases/new.html.erb
<h1><%= t('caseNew') %></h1>
<%= render 'form', case: @case %>