config/routes.rb
Rails.application.routes.draw do

  resources :executes
  resources :keywords
  resources :platforms

  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
  }

  resources :users
  resources :manages
  resources :roles, except: :show
  resources :projects
  resources :assigns
  resources :suites , except: :show do
    resources :cases , except: :show do
      resources :steps, except: [:show, :edit]
    end
  end

  resources :builds , except: :show do
    resources :plans , except: :show do
      resources :case_plan , except: :show
    end
  end

  resources :message_folders do
    resources :messages
  end

  post '/set_current_project', to: 'application#set_current_project', as: :set_current_project
  post '/save_execution', to: 'executes#save_execution', as: :save_execution
  get 'case_plan/index'
  get '/executes_history', to: 'executes#index_history', as: :index_history
  get '/executes_history/:id', to: 'executes#show_index_history', as: :show_index_history


  root 'welcome#index'

end

app/models/assign.rb
class Assign < ApplicationRecord
end

app/models/build.rb
class Build < ApplicationRecord

  belongs_to :project
  has_many :plans

end

app/models/case.rb
class Case < ApplicationRecord

  belongs_to :suite
  has_many :steps
  has_many :case_plans

end

app/models/case_plan.rb
class CasePlan < ApplicationRecord
  belongs_to :user
  belongs_to :case
  belongs_to :plan
end

app/models/execute.rb
class Execute < ApplicationRecord
end

app/models/execute_case.rb
class ExecuteCase < ApplicationRecord

  belongs_to :user
  has_many :execute_step

end

app/models/execute_step.rb
class ExecuteStep < ApplicationRecord

  belongs_to :execute_case

end

app/models/keyword.rb
class Keyword < ApplicationRecord
end

app/models/manage.rb
class Manage < ApplicationRecord

  # Relaciones
  belongs_to :role
  belongs_to :zone

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
end

app/models/plan.rb
class Plan < ApplicationRecord

  belongs_to :build
  has_many :case_plans

end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :assign
  has_many :builds

end

app/models/role.rb
class Role < ApplicationRecord

  # Relaciones
  has_many :users
  has_many :manages


  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10}

end

app/models/step.rb
class Step < ApplicationRecord

  belongs_to :case

end

app/models/suite.rb
class Suite < ApplicationRecord

  has_many :cases

end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Dirty
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable

  # attr_accessor :manages

  # Relaciones
  belongs_to :role
  has_many :assign
  has_many :message_folders
  has_many :case_plans

  after_initialize do |user|
    unless user.role.nil?
      @manages ||= Manage.where(:role_id => user.role.id)
    end
  end


  def CanRead?(zone)
    # @CanRead = Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canRead)
    # @manages.where(:zone_id => zone).select(:canRead).first
    @manages.select { |manage| manage.zone_id == zone }.first[:canRead]
  end

  def CanCreate?(zone)
    # @CanCreate ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canCreate)
    @manages.select { |manage| manage.zone_id == zone }.first[:canCreate]
  end

  def CanUpdate?(zone)
    # @CanUpdate ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canUpdate)
    @manages.select { |manage| manage.zone_id == zone }.first[:canUpdate]
  end

  def CanDelete?(zone)
    # @CanDelete ||= Manage.where(:role_id => self.role.id, :zone_id => zone).select(:canDelete)
    @manages.select { |manage| manage.zone_id == zone }.first[:canDelete]
  end


  private

  # def getManage
  #   @manages ||= Manage.where(:role_id => self.role.id)
  # end

end

app/models/zone.rb
class Zone < ApplicationRecord

  # Relaciones
  has_many :manages

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :param_build

  # GET /plans
  def index
    @plans = Plan.where('build_id' => @build.id)
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  def create
    @plan = Plan.new(plan_params)
    @plan.build = @build

    if @plan.save
      flash[:success] = t('planCreated')
      redirect_to build_plans_path
    else
      flash[:error] = t('planCreatedError')
      redirect_to new_build_plan_path
    end
  end

  # PATCH/PUT /plans/1
  def update
    if @plan.update(plan_params)
      flash[:success] = t('planEdited')
      redirect_to build_plans_path
    else
      flash[:error] = t('planEditedError')
      redirect_to new_build_plan_path
    end
  end

  # DELETE /plans/1
  def destroy
    if @plan.destroy
      flash[:success] = t('planDeleted')
      redirect_to build_plans_path
    else
      flash[:error] = t('planDeletedError')
      redirect_to build_plans_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:active, :public, :name, :description)
    end

  def param_build
    @build = Build.find(params[:build_id])
  end

end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/plans/_form.html.erb
<div class="forms center-block" style="width: 60%;">
  <%= form_for([@build, @plan], :html => {:class => 'form-horizontal'}) do |f| %>
      <% if @plan.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

            <ul>
              <% @plan.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :fname, t('planName'), class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name, placeholder: t('planName'), class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fdescription, t('planDescription'), class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :description, placeholder: t('planDescription'), class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :factive, t('planActive'), class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.check_box :active, placeholder: t('planActive'), class: 'check' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fpublic, t('planPublic'), class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.check_box :public, placeholder: t('planPublic'), class: 'check' %>
        </div>
      </div>

      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit t('save'), class: "btn btn-default btn-primary" %>
        <%= link_to t('back'), build_plans_path(build_id: @build.id), class: "btn btn-default" %>
      </div>

  <% end %>
</div>

app/views/plans/edit.html.erb
<h1><%= t('planEdit') %> <%= @plan.name %> </h1>
<%= render 'form', plan: @plan %>

app/views/plans/index.html.erb
<h1><%= t('plans') %></h1>

<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th><%= t('planName') %></th>
      <th><%= t('planActive') %></th>
      <th><%= t('planPublic') %></th>
      <th colspan="4"><%= t('planDescription') %></th>
    </tr>
    </thead>

    <tbody>
    <% @plans.each do |plan| %>
        <tr>
          <td class="col-md-3"><%= plan.name %></td>
          <td class="col-md-1"><%= plan.active %></td>
          <td class="col-md-1"><%= plan.public %></td>
          <td class="col-md-6"><%= plan.description %></td>
          <td title="<%= t('planEditList') %>"><%= link_to fa_icon("pencil") , edit_build_plan_path(build_id: plan.build.id, id: plan.id) %></td>
          <td title="<%= t('planDeleteList') %>"><%= link_to fa_icon("remove") , build_plans_path(build_id: plan.build.id, id: plan.id), method: :delete, data: { confirm: t('confirmDelete') } %></td>
          <td title="<%= t('planAssignList') %>"><%= link_to fa_icon("share") , build_plan_case_plan_index_path(build_id: plan.build.id, plan_id: plan.id) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/plans/new.html.erb
<h1><%= t('planNew') %></h1>
<%= render 'form', plan: @plan %>